### ISSUE TITLE
GCS: Session management sometimes gets stuck in handshake

### ISSUE THREAD

**Issue by tracernz** [d-ronin/dRonin#1384] opened 2016-09-24 07:52 UTC
I have seen this quite a few times lately. Disconnect/reconnect doesn't help, restarting GCS doesn't help, rebooting the board does help. On the GCS side:
![fuuu](http://i.imgur.com/nlxXYOS.png)

Weird that the flight side is showing 0 data rate too... Objects are being received just fine and the CPU load is 32% so not pegged.

After rebooting the board to fix it... still 0 data rate on the flight side:
![fail](http://i.imgur.com/kUuwOx7.png)

**Comment by mluessi** [comment] 2016-09-24 10:48
I think this is a duplicate of https://github.com/TauLabs/TauLabs/issues/1418

**Comment by jpbarraca** [comment] 2016-11-01 00:39
I think I'm having a related problem when using a Sparky2 in MacOS with Quixote.
The FC reports data, sensors are received and scopes update, but:
- It never "gets link"
- The GCSTelemetryStats object is updating with strange values: Very unstable RXDataRate (highs and lows or 0), TXFailures keeps increasing. Status is Connected.
- In linux (ubuntu 16.04, Virtualbox) gcs seems to operate correctly

UPDATE:
- Also happens with a CC3D
- Using MacOS 10.12.1
- The same FC worked perfectly in 10.11.x

**Comment by mlyle** [comment] 2017-06-28 02:54
I think I plan to close this in favor of #1571, as it's the core obvious repro case.

**Closed as completed by mlyle** 2017-06-28 02:54 UTC
Labels: bug, flight, status/requires-investigation

**Comment by tracernz** [comment] 2017-06-28 03:47
It's a different issue (USB peripheral on flight side vs. session management handshake on ? side for this one)?

**Comment by mlyle** [comment] 2017-06-28 04:01
I think/thought session management is correct, and this glitch happens when USB falls apart (e.g. it's OS/version dependent, seems to relate to hotplug, etc).  That is, this seems to be a more general description of  #1571 --- am I wrong?

**Comment by tracernz** [comment] 2017-06-28 05:19
No this is when we're talking and sending objects back and forth but the session handshake gets "stuck".

**Comment by mlyle** [comment] 2017-06-28 05:22
OK, I've not seen that.  Can it be repro'd?

**Comment by tracernz** [comment] 2017-06-28 05:23
I've not found a reliable repro (I have tried a little bit), just seen it happen very occasionally.
