### ISSUE TITLE
after auto tune stabilization page showing default pids

### ISSUE THREAD

**Issue by redparchel** [d-ronin/dRonin#1249] opened 2016-08-28 02:35 UTC
- Seen in version (release version or githash): Release-20160720.1: 20160723-74b7422c
- On flight controller (if applicable): naze32 rev6c

Issue details:
start on "stabilization" tab, connect to FC, go through prompted autotune wizard. after clicking "done" on the autotune wizard the stabilization page still shows the default pids (i believe it should display the new pids read from the board) i clicked save (out of habit) saving the defaults back to the board and undoing the autotune pids.

**Comment by mlyle** [comment] 2016-09-01 03:32
I can't reproduce this-- when I run autotune, my stabilization page appears to update immediately.

Was tested on a naze32 clone (quanum pico)

**Comment by mlyle** [comment] 2016-09-05 23:00
Closing because no-repro :/

**Closed as completed by mlyle** 2016-09-05 23:00 UTC
Labels: status/unconfirmed
