### ISSUE TITLE
Record Symbols for Breakpad

### ISSUE THREAD

**Issue by dustin** [d-ronin/dRonin#143] opened 2015-12-04 18:31 UTC
In order to use breakpad, we have to have symbols exported from the build and available for the minidump processor.  As we're having crashes go to autotown, it makes sense to send the symbol tables up as well.  Perhaps this can also lead to analysis automatically occurring there.

**Comment by dustin** [comment] 2015-12-04 18:32
Putting this comment here since I don't know where else to put it.  :/

https://chromium.googlesource.com/breakpad/breakpad/+/master/docs/getting_started_with_breakpad.md

**Comment by tracernz** [comment] 2015-12-04 18:35
Yep, if we can keep this nice and simple and get it hooked into Jenkins it would be grand.

**Comment by dustin** [comment] 2015-12-04 18:39
I don't know what the thing looks like, but if it's just a file, I can make a tool that can be placed on builders along with a file for auth that hands it over.

**Comment by dustin** [comment] 2015-12-17 22:46
I hope this is easy.  I have a feeling we might regret having ~1/3 of the crash infrastructure, but having the symbols be useless.

**Comment by tracernz** [comment] 2015-12-18 10:28
We keep the git hash so I think that should allow us to build symbols for each dump.

**Comment by mlyle** [comment] 2015-12-18 17:49
We need to do it at original build time.  We have no guarantee for
byte-for-byte, address-for-address reproducibility just by having the same
code.

**Comment by tracernz** [comment] 2015-12-19 21:57
Yeah, but it will give us a shot at using our existing crash-dump data until we get something together to dump symbols from releases. ;-)

**Comment by mlyle** [comment] 2015-12-19 22:13
@tracernz have you seen this work?  Because I doubt it will work.

**Comment by tracernz** [comment] 2015-12-19 23:36
Nope, haven't tried. Will look into getting this sorted in the coming week if nobody else is?

**Comment by mlyle** [comment] 2015-12-19 23:38
If you have time, a recipe I could use as part of the package build to get things would be nice.

**Comment by mlyle** [comment] 2016-01-06 20:17
Needs appropriate documentation as part of build process and/or hooking it into the build.

**Comment by mlyle** [comment] 2016-03-24 22:05
Won't be further improving this before samsara; deferring.

**Comment by mlyle** [comment] 2016-07-22 17:15
This was done for OSX, but Windows still needs to have its path forward determined.

**Comment by mlyle** [comment] 2016-07-22 17:16
Closed in favor of #290 (more specific bug)

**Closed by mlyle** 2016-07-22 17:16 UTC
Labels: build/infrastructure, gcs, ready
