### ISSUE TITLE
CC3D:motor output channel assignment discontinuity

### ISSUE THREAD

**Issue by pug398** [d-ronin/dRonin#904] opened 2016-04-08 22:46 UTC
I updated a CC3D that had a slightly unusual channel assignment in that channel 1 is dead so 2,3,4,5 are used. After updating it flies fine and mixer is set correctly except all of the motor output channel assignments say "None" in vehicle setup.

**Comment by mlyle** [comment] 2016-04-09 00:52
Just to clarify-- you didn't need to change settings-- it just displayed in the UI wrong?

I suspect this is a cousin of #315, then.

**Comment by pug398** [comment] 2016-04-09 01:40
Yes I changed nothing. It was setup and flying and I did a successful upgrade and it continued to fly. Later I noticed it had None for the Motor output channels. I have done several upgrade cycles back and forth and also manual import/export. Settings are holding now so not sure what happened.

**Comment by mlyle** [comment] 2016-04-26 21:49
I'm gonna go ahead and close this one duplicate.  I'm not sure whether it's a duplicate of #315, or #919-ish issues, or #747... (or that hopefully all of these have a common cause which seems likely)  but it almost certainly is one of these manifesting.

**Closed as completed by mlyle** 2016-04-26 21:49 UTC
Labels: duplicate, gcs, flight
