### ISSUE TITLE
GCS no longer displaying the file dialog box

### ISSUE THREAD

**Issue by droidicus** [d-ronin/dRonin#462] opened 2016-01-17 18:37 UTC
After using the GCS for a while (5-10 minutes usually), the GCS will no longer open a file dialog box when it is needed (log file save, UAVO import/export, firmware file selection, etc). Closing and restarting the GCS fixes the issue. On Windows 10, this happens frequently, but seemingly randomly.

**Comment by mlyle** [comment] 2016-01-17 18:58
Is this a duplicate of #236?

**Comment by droidicus** [comment] 2016-01-17 21:02
I don't believe so, I am not seeing a window in front or behind.

**Comment by mlyle** [comment] 2016-01-17 23:19
So you've moved the window around and looked for it and can't find it?

**Comment by droidicus** [comment] 2016-01-18 00:13
90% sure at least.

**Comment by droidicus** [comment] 2016-01-18 02:12
Reproduced, no window is shown above or below. None on taskbar, nor shown in an alt-tab.

**Comment by tracernz** [comment] 2016-01-18 02:18
Can't repro on Lunix. The file dialogs do start opening underneath the main window after a while though, may be related.

**Comment by droidicus** [comment] 2016-01-18 04:04
Not to muddy the waters, but another possibly related issue... Sometimes I can successfully get to the dialog box, but it will not let me open or save a file. I can click the open/save button, highlight the filename and hit enter, etc. No dice.

**Comment by mlyle** [comment] 2016-06-25 01:09
@droidicus Have you seen this at all lately?  Is it still present?  I cannot repro / am inclined to close

**Comment by tracernz** [comment] 2016-06-25 01:28
I haven't seen it recently because I added that code to auto-load the correct firmware back when we started on upgrader work. It probably still happens when saving partitions, log files etc. though.

**Comment by mlyle** [comment] 2016-06-25 01:30
@tracernz-- this isn't the pop-behind one.  This is a completely missing dialog.  do you mean completely-missing or pop-behind?

**Comment by tracernz** [comment] 2016-06-25 01:35
Oh yep, you're right, never seen this one.

**Closed** 2016-07-22 17:27 UTC
Labels: bug, gcs, status/requires-investigation, usability
