### ISSUE TITLE
Investigate chopping effect of loiter_errordecayalpha during 1/4 stick - 1/2 stick loiter

### ISSUE THREAD

**Issue by pug398** [d-ronin/dRonin#37] opened 2015-11-25 04:49 UTC
Heavy chopping of loiter path at 1/4 stick loiter. Moderate at 1/2 stick. Smooth at full stick. Reducing LoiterErrorDecayConstant from 0.33 to 0.05 mitigates the effect and allows smooth slow loiter.

**Comment by mlyle** [comment] 2015-11-25 04:51
Yup, I've got your email.  Sorry I've been slow to answer, but this obviously needs tweaking.  I need to find root cause though, because moving this so far makes me nervous.

**Comment by mlyle** [comment] 2015-12-10 18:33
#120 merged.  Will look at loiter more systematically in the future.

**Closed by mlyle** 2015-12-10 18:33 UTC
Labels: difficulty/medium, flight, status/pr-open
