### ISSUE TITLE
Conversion warning

### ISSUE THREAD

**Issue by dustin** [d-ronin/dRonin#1122] opened 2016-07-16 19:07 UTC
This wasn't an error to the user, but may indicate incomplete conversion.

Error on attempting to adapt ActuatorSettings (/base/data/home/apps/s~dronin-autotown/py:1.394239192895852089/convert.py:71)
Traceback (most recent call last):
  File "/base/data/home/apps/s~dronin-autotown/py:1.394239192895852089/convert.py", line 45, in post
    actuatorSettings = imported['UAVO_ActuatorSettings']
KeyError: 'UAVO_ActuatorSettings'

**Comment by mlyle** [comment] 2016-07-16 19:20
Do you have the hashes this happened with?

It's probably a duplicate of #848-- someone has a build from a pull request or their own unmerged branch, and we fall back to using the last release's UAVOs.  

Alternatively, if they've never saved actuatorsettings before upgrade, this will happen.

**Comment by dustin** [comment] 2016-07-16 21:51
No, logging is insufficient here.  :(

**Closed as completed** 2016-07-16 22:01 UTC
Labels: duplicate, cloud ⛈

**Comment by tracernz** [comment] 2016-07-17 05:50
Should instrument the code with python's logging class so this will be better in future.
